// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoG0yjuokE59mo5_YLfDJN7iC3lDF8_Zg',
    appId: '1:513130488309:web:27b2354f037895e48500bc',
    messagingSenderId: '513130488309',
    projectId: 'gcc-connect-44b69',
    authDomain: 'gcc-connect-44b69.firebaseapp.com',
    storageBucket: 'gcc-connect-44b69.firebasestorage.app',
    measurementId: 'G-WTDG07FTX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvZ6O-B7rHmycjy63SPNQkLzVam-5eohs',
    appId: '1:513130488309:android:0ff433cb4fb119b88500bc',
    messagingSenderId: '513130488309',
    projectId: 'gcc-connect-44b69',
    storageBucket: 'gcc-connect-44b69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUXQQf8uZi1-ya--VgP0QvtojvFkhwoSs',
    appId: '1:513130488309:ios:2edd8d195ef5f4548500bc',
    messagingSenderId: '513130488309',
    projectId: 'gcc-connect-44b69',
    storageBucket: 'gcc-connect-44b69.firebasestorage.app',
    iosBundleId: 'umer.com.gcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUXQQf8uZi1-ya--VgP0QvtojvFkhwoSs',
    appId: '1:513130488309:ios:2edd8d195ef5f4548500bc',
    messagingSenderId: '513130488309',
    projectId: 'gcc-connect-44b69',
    storageBucket: 'gcc-connect-44b69.firebasestorage.app',
    iosBundleId: 'umer.com.gcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoG0yjuokE59mo5_YLfDJN7iC3lDF8_Zg',
    appId: '1:513130488309:web:04f23fa0620369098500bc',
    messagingSenderId: '513130488309',
    projectId: 'gcc-connect-44b69',
    authDomain: 'gcc-connect-44b69.firebaseapp.com',
    storageBucket: 'gcc-connect-44b69.firebasestorage.app',
    measurementId: 'G-FS4D7QXD4D',
  );
}
